ktor:
    application:
        modules:
            - com.novel.ApplicationKt.module
    deployment:
        port: 8080
    development: true  # Set to false for production

# Database configuration
database:
    # PostgreSQL configuration
    postgres:
        url: "$DB_URL:jdbc:postgresql://localhost:5432/novel_db"
        driver: "org.postgresql.Driver"
        user: "$DB_USER:novel_user"
        password: "$DB_PASSWORD:novel_password"

    # HikariCP connection pool settings
    hikaricp:
        maxPoolSize: 10
        minIdle: 2
        autoCommit: false
        transactionIsolation: "TRANSACTION_REPEATABLE_READ"
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000

    # Flyway configuration
    flyway:
        baselineOnMigrate: true
        locations: "classpath:db/migration"
        validateMigrationNaming: true

# JWT configuration
jwt:
    domain: "https://jwt-provider-domain/"
    audience: "jwt-audience"
    realm: "Novel MVP App"
    secret: "$JWT_SECRET:your-256-bit-secret-your-256-bit-secret" # Use environment variable
    issuer: "http://localhost:8080"
    accessTokenExpiry: 3600000  # 1 hour in milliseconds
    refreshTokenExpiry: 2592000000  # 30 days in milliseconds