ktor:
    application:
        modules:
            - com.novel.ApplicationKt.module
    deployment:
        port: 8080
    development: true  # Set to false for production

# Database configuration
database:
    # PostgreSQL configuration
    postgres:
        url: "$DB_URL:jdbc:postgresql://localhost:5432/your-story-postgres"
        driver: "org.postgresql.Driver"
        user: "$DB_USER:your_story_user"
        password: "$DB_PASSWORD:your_story_password"

    # HikariCP connection pool settings
    hikaricp:
        maxPoolSize: 10
        minIdle: 2
        autoCommit: false
        transactionIsolation: "TRANSACTION_REPEATABLE_READ"
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000

    # Flyway configuration
    flyway:
        baselineOnMigrate: true
        locations: "classpath:db/migration"
        validateMigrationNaming: true

# JWT configuration
jwt:
    domain: "https://jwt-provider-domain/"
    audience: "jwt-audience"
    realm: "ktor sample app"
    secret: "your-256-bit-secret-your-256-bit-secret" # Only use for development

# OAuth configuration
oauth:
    google:
        clientId: "$GOOGLE_CLIENT_ID:your-google-client-id"
        clientSecret: "$GOOGLE_CLIENT_SECRET:your-google-client-secret"